services:
  - type: web
    name: centuryply-audit-webapp-final-v3-1
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn centuryply_audit_webapp:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.10.14
    autoDeploy: true
